name: IriunClone

options:
  bundleIdPrefix: com.mike

settings:
  BASE_SDK: iphoneos
  IPHONEOS_DEPLOYMENT_TARGET: 15.0

targets:
  IriunClone:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: .
    info:
      path: info.plist
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.mike.iriunclone
      PRODUCT_NAME: IriunClone
      SWIFT_VERSION: 5.0
      TARGETED_DEVICE_FAMILY: "1"
    scheme:
      testTargets: []

